### ISSUE TITLE
Please have a logo with Twitter specific dimensions 

### ISSUE THREAD

**Issue by developerkevin** [EthereumCommonwealth/Callisto-Media-Kit#1]
Many of the ETC logos are too large to scale properly on Twitter, and end up getting chopped off. If you could make sure to have a **Callisto logo** with the dimensions specifically for Twitter that would help out a lot when promotion time comes. 

I did a quick search and it looks like 506 x 253 pixels is their perfect fit. :slightly_smiling_face:

**Comment by Dexaran** [comment]
Thank you for the useful feedback. We will consider adding it soon.
