### ISSUE TITLE
Create larger version of minified-logo for Twitter

### ISSUE THREAD

**Issue by developerkevin** [EthereumCommonwealth/Callisto-Media-Kit#3]
It would be beneficial to have the ["minified"](https://github.com/EthereumCommonwealth/Callisto-Media-Kit/blob/master/minified-logo.jpg) logo, (with the Logo and Callisto text) in the Twitter ratio also. It would have better resolution, instead of trying to blow up the mini logo.

**Comment by ethernyt** [comment]
What about this ?

https://ethernyt.github.io/index.html

Like it ? :D

**Comment by yograterol** [comment]
I like the new logo. I like both logos, but the yin yang is cool.

**Comment by ethernyt** [comment]
Using the yin yang has many many advantages ...

Which logo do you want to use ? @Dexaran @yograterol ?

**Comment by ethernyt** [comment]
Using the yin yang has many many advantages ...

Which logo do you want to use ? @Dexaran @yograterol ?

I suggest using one - not 2 different in the repo ...

I could design some good media including videos and would be very motivated by using the yinyang. I need your opinion before i would starting something what is not accepted by the dev team :D

Btw:. @yograterol - the font is not important - we could even remove it here in the repo. Most people will use only the logo. If they need better media for the yinyang they could simply take a look at google -> pictures and steal one good looking CC0 from other designers.

I need the opinion from @Dexaran which logo to use. Using both is contraproductive.

**Comment by yograterol** [comment]
@ethernyt I vote for yin yang.

You're right about the advantages.

About the font, if the logo will have text, the font should be cool.

The landing page, I added you as a collaborator of https://github.com/EthereumCommonwealth/Callisto-Website, please upload https://ethernyt.github.io/index.html in the official repo to deploy it and link callisto.network domain.

**Comment by ethernyt** [comment]
Okay - i will do it tomorrow if it's okay.

Did you see https://github.com/EthereumCommonwealth/Callisto-Website ?

Shall we use this font ? I want to add that for the first steps it's really not important for the upcoming community which font is exactly used. In the end only the logo is important - without text. Also i would suggest deleting all the other logo variants in the repo fast and announce the yinyang as official symbol. That would be the easiest :D

**Comment by ethernyt** [comment]
Additionally i can make derived yinyang graphics + callisto text and a video fast. It would be finished until end of week and could upload in in the media-kit repo.

**Comment by ethernyt** [comment]
@yograterol Can we use the font from https://ethernyt.github.io/index.html ?

**Comment by yograterol** [comment]
> Did you see https://github.com/EthereumCommonwealth/Callisto-Website ?

Yes 

> Additionally i can make derived yinyang graphics + callisto text and a video fast. It would be finished until end of week and could upload in in the media-kit repo.

It could be awesome

> Can we use the font from https://ethernyt.github.io/index.html ?

The same font is cool, you could import it from that repo.

**Comment by ethernyt** [comment]
Very good - that's all what i need to start working immediately.

So if @Dexaran is fine with that to, it's official ...

Whoever reads these lines now - Callisto's Logo is one of the most powerful logos on earth now. The Yinyang.

The asian market will freak out.

**Comment by ethernyt** [comment]
Website is deployed @yograterol.

Please do the following:

* Calisto-Website -> Repository Settings -> Settings Tab -> Github Pages Section -> Master-Branch -> Save
* Fire up a browser and go to http://ethereumcommonwealth.github.io/Callisto-Website

More instructions on https://pages.github.com/ -> Project Site > Start from scratch

**Comment by ethernyt** [comment]
Website is deployed @yograterol.

Please do the following:

* Calisto-Website -> Repository Settings ->  Github Pages Section -> Master-Branch -> Save
* Open browser: http://ethereumcommonwealth.github.io/Callisto-Website/index.html

More instructions on https://pages.github.com/ -> Project Site > Start from scratch

**Comment by Cryptosophies** [comment]
Sorry for interupting but what about this one ? Made with a professionnal designer. We can make modifications and export for every case (small, medium or huge). I hope you like it.

![logo callisto](https://user-images.githubusercontent.com/36563455/36789416-c66a7f58-1c91-11e8-9f56-f34749ffc5cb.png)

**Comment by Cryptosophies** [comment]
As for the Yin-Yang symbol, of course it's interesting but it has major disadvantages and is an extremely risky move.

**Comment by developerkevin** [comment]
The Twitter sized logo would really benefit the project right now if you want to establish the Callisto brand. 👍
